### ISSUE TITLE
报错runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [icyxp/kubernetes-dashboard-ldap#3]
```shell
2020/11/18 15:13:55 >>>>>>>>>>>>>>>>>>init cluster[local] k8s client>>>>>>>>>>>>>>>>>>


2020/11/18 15:13:55 [Recovery] 2020/11/18 - 15:13:55 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x44b659)
/usr/local/go/src/runtime/signal_unix.go:695 (0x44b4a8)
/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20191029005444-8e4128053008+incompatible/kubernetes/clientset.go:237 (0x11b6c9d)
/go/src/dashboard-ldap/controller/login.go:232 (0x11b6c94)
/go/src/dashboard-ldap/controller/login.go:99 (0x11b54a3)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9b3d6a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x9c746f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9b3d6a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0x9c65a0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9b3d6a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9bdb45)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9bd25c)
/usr/local/go/src/net/http/server.go:2807 (0x713ad2)
/usr/local/go/src/net/http/server.go:1895 (0x70f44b)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x467400)
```

**Comment by ZhangSIming-blyq** [comment]
[GIN] 2020/11/18 - 15:13:45 | 200 |     295.953µs |    172.62.119.0 | GET      "/login"
[GIN] 2020/11/18 - 15:13:46 | 200 |    1.797644ms |    172.62.119.0 | GET      "/statics/images/favicon.ico"
2020/11/18 15:13:48 >>>>>>>>>>>>>>>>>>>>>>>>>> Distinguished Name: uid=zhangsiming,ou=users,dc=shannonai,dc=com <<<<<<<<<<<<<<<<<<<<<<<<
[GIN] 2020/11/18 - 15:13:48 | 200 |   36.729966ms |    172.62.119.0 | POST     "/login"
2020/11/18 15:13:55 >>>>>>>>>>>>>>>>>>>>>>>>>> Distinguished Name: uid=zhangsiming,ou=users,dc=shannonai,dc=com <<<<<<<<<<<<<<<<<<<<<<<<
2020/11/18 15:13:55 >>>>>>>>>>>>>>>>>>init cluster[local] k8s client>>>>>>>>>>>>>>>>>>


2020/11/18 15:13:55 [Recovery] 2020/11/18 - 15:13:55 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x44b659)
/usr/local/go/src/runtime/signal_unix.go:695 (0x44b4a8)
/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20191029005444-8e4128053008+incompatible/kubernetes/clientset.go:237 (0x11b6c9d)
/go/src/dashboard-ldap/controller/login.go:232 (0x11b6c94)
/go/src/dashboard-ldap/controller/login.go:99 (0x11b54a3)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9b3d6a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x9c746f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9b3d6a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0x9c65a0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9b3d6a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9bdb45)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9bd25c)
/usr/local/go/src/net/http/server.go:2807 (0x713ad2)
/usr/local/go/src/net/http/server.go:1895 (0x70f44b)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x467400)

[GIN] 2020/11/18 - 15:13:55 | 500 |   66.291201ms |    172.62.119.0 | POST     "/login"

**Comment by icyxp** [comment]
Give your configmap.yaml configuration file，Confirm whether the local cluster apiserver can communicate
