### ISSUE TITLE
不知道能否支持token登录kubeapps呢

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [icyxp/kubernetes-dashboard-ldap#4]
kubeapps也是token登录，希望支持

**Comment by ZhangSIming-blyq** [comment]
或者告诉我怎么二次开发呢

**Comment by icyxp** [comment]
Do you want to use token or AD to login，I'll think about it。I will open source later, thank you for your attention！

**Comment by ZhangSIming-blyq** [comment]
> Do you want to use token or AD to login，I'll think about it。I will open source later, thank you for your attention！

Sure, kubeapps use token to authorization just like the way of kube-dashbaord, see below:
![image](https://user-images.githubusercontent.com/58658883/99754369-38b27000-2b23-11eb-8181-8e8b69083e68.png)

**Comment by icyxp** [comment]
release `icyboy/k8s-mutiboard-ldap:2.0.0` can support  token login
